### ISSUE TITLE
When trying to launch on debian 10

### ISSUE THREAD

**Issue by mundusnine** [srevinsaju/discord-appimage#1]
I get this error in the console:
![image](https://user-images.githubusercontent.com/29337013/93244433-b939a680-f757-11ea-95c5-493117e03d6e.png)

**Comment by srevinsaju** [comment]
@mundusnine this is a long, unfixed bug in electron itself. One solution is to

```bash
./Discord*.AppImage --appimage-extract
cd squashfs-root
sudo chmod 4755 chrome-sandbox
./AppRun
```

Let me know if it works

**Comment by mundusnine** [comment]
Ok so when starting the appimage with --no-sandbox it works; I tried with your method but no cigar.

Thanks !
