### ISSUE TITLE
Discord 0.0.17 now avalible. 

### ISSUE THREAD

**Issue by MintMain21** [srevinsaju/discord-appimage#3]
So......I'm not sure if I have to tell you, but there's a new version of Discord available, and now the current appimage won't work. 

Just a heads up. I love what you do. I've had a better time with your appimages than with the Flatpak and .deb packages, so know that you're doing great work.

**Comment by MintMain21** [comment]
Thank you.

**Comment by srevinsaju** [comment]
Thanks for raising the issue. GitHub suspends automatic scheduled builds after few weeks of inactivity. So I just had fire it up. Thanks again! :heart:

**Comment by NagareHoshi** [comment]
Thank YOU too for this and for being awesome!

**Comment by remi-garcia** [comment]
@srevinsaju I believe automatic scheduled builds are suspended again

**Comment by srevinsaju** [comment]
@remi-garcia thanks for the bump, looks like the builds were failing, pushed a fix and new builds are out!

**Comment by remi-garcia** [comment]
Thank you for the reactivity!
I use a script to update my AppImage and it does not work anymore. Since I do not handle that manually I might have forgotten how it should be, but AppImage should not be available here? https://github.com/srevinsaju/discord-appimage/releases/tag/stable

This probably should have its own issue, sorry.

**Comment by remi-garcia** [comment]
It seems that something goes wrong in CI: https://github.com/srevinsaju/discord-appimage/actions/runs/11027679827/job/30626438785
```
Uploading release artifacts
  Error: discord-continuous-x86_64.AppImage doesn't match any files
```

**Comment by remi-garcia** [comment]
@srevinsaju (I am not sure you saw it, sorry for the ping)
